language: node_js
node_js:
    - "0.10"
    - "0.12"
sudo: required
cache:
  directories:
    - node_modules
env:
    - DB=mongodb
services:
    - mongodb
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq beanstalkd
    - sudo beanstalkd -d -l 127.0.0.1 -p 11300
script:
    - node_modules/.bin/mocha test/test.js

