language: node_js
node_js:
    - "0.10"
    - "0.12"
sudo: required
cache:
  directories:
    - node_modules
env:
    - DB=mongodb
services:
    - mongodb
script:
    - node_modules/.bin/mocha test/test.js

